compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  8x8:
    npmPublishRegistry: "https://artifactory.es.8x8.com/artifactory/api/npm/npm-repository/"
    npmRegistryServer: "https://artifactory.es.8x8.com/artifactory/api/npm/npm-repository/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
