const THEME_NAME = 'contextMenu';
const CONTEXT_MENU_SHOW = 'OXYGEN_CONTEXT_MENU_SHOW';
const CONTEXT_MENU_HIDE = 'OXYGEN_CONTEXT_MENU_HIDE';

export { CONTEXT_MENU_SHOW, CONTEXT_MENU_HIDE, THEME_NAME };
